version: '3'

vars:
  PYTHON: uv run python
  YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}

silent: true

tasks:
  sync:
    desc: Sync Python deps with uv
    cmds:
      - uv sync --frozen || uv sync

  render:
    desc: Render site to index.html (respects CI for minification)
    cmds:
      - task: sync
      - >
        {{.PYTHON}} ./generate.py
    env:
      YOUTUBE_API_KEY: "{{.YOUTUBE_API_KEY}}"

  build:
    desc: Build static site (alias to render)
    cmds:
      - task: render

  clean:
    desc: Remove generated artifacts
    cmds:
      - rm -f index.html
