---
menu:
  - name: 'About me'
    page: 'index'
  - name: 'Curriculum Vitae (CV/Resume)'
    page: 'cv'
  - name: 'Projects'
    pages:
      - name: 'Dummy placeholder'
        page: 'project1'
  # TODO: Uncomment after first blog post
  # - name: 'Blog'
  #   page: 'blog'
pages:
  - name: ''

  # - name: 'blog'
  #   content: {}