---

name: Preparation
on:
  pull_request:
    branches: [ master ]

jobs:
  preparation:
    name: Artifacts preparation
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Run generation script
        run: |
          pip install -r scripts/requirementss.txt
          python scripts/generate.py
      - uses: EndBug/add-and-commit@v4
        with:
          add: '*.html'
          author_name: DovnarAlexander
          author_email: 29893487+DovnarAlexander@users.noreply.github.com
          force: true
          signoff: true
          message: 'Generated HTML pages'
